In [1]:
import pandas as pd


df = pd.read_csv('../Datasets/Churn Prdiction Data/churn-bigml-80.csv')


df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [ ]:
%pip install scikit-learn

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('../Datasets/Churn Prdiction Data/churn-bigml-80.csv')

for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
        df[col] = df[col].fillna(df[col].median())
    else:
        df[col] = df[col].fillna(df[col].mode()[0])

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)
IQR = Q3 - Q1
mask = ~((df[numeric_cols] < (Q1 - 1.5 * IQR)) | (df[numeric_cols] > (Q3 + 1.5 * IQR))).any(axis=1)
df_cleaned = df[mask].copy()

categorical_cols = df_cleaned.select_dtypes(include=['object', 'bool']).columns
df_cleaned = pd.get_dummies(df_cleaned, columns=categorical_cols, drop_first=True)

scaler = StandardScaler()
final_numeric = df_cleaned.select_dtypes(include=['int64', 'float64', 'float32']).columns
df_cleaned[final_numeric] = scaler.fit_transform(df_cleaned[final_numeric])

df_cleaned.to_csv('Task2_Cleaned_Churn_Data.csv', index=False)
print("Task 2 Complete! Cleaned data saved.")
df_cleaned.head()

Task 2 Complete! Cleaned data saved.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19328\1307010894.py:20: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df_cleaned.select_dtypes(include=['object', 'bool']).columns

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,...,State_UT,State_VA,State_VT,State_WA,State_WI,State_WV,State_WY,International plan_Yes,Voice mail plan_Yes,Churn_True
0,0.714450,-0.531088,1.242684,1.621338,0.502728,1.621625,-0.065305,-0.048267,-0.065131,0.883286,...,False,False,False,False,False,False,False,False,True,False
1,0.177014,-0.531088,1.316042,-0.350505,1.179757,-0.350792,-0.103630,0.156468,-0.103099,1.080186,...,False,False,False,False,False,False,False,False,True,False
2,0.944780,-0.531088,-0.591277,1.207918,0.711045,1.208090,-1.602336,0.514755,-1.602855,-0.783264,...,False,False,False,False,False,False,False,False,False,False
3,-0.411606,-0.695111,-0.591277,2.274809,-1.528358,2.274988,-2.798476,-0.611289,-2.798863,-0.087007,...,False,False,False,False,False,False,False,True,False,False
4,-0.641935,-0.531088,-0.591277,-0.253342,0.658966,-0.253292,-1.055702,1.128961,-1.054685,-0.289998,...,False,False,False,False,False,False,False,True,False,False